name: Build Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker build -t $REPOSITORY_NAME .
          docker tag $REPOSITORY_NAME:latest $ECR_REGISTRY/$REPOSITORY_NAME:${{ github.ref_name}}
          docker push $ECR_REGISTRY/$REPOSITORY_NAME:${{ github.ref_name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
