version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - npm install -g typescript
      - npm install -g esbuild
  build:
    commands:
      - sam build
      - sam package --s3-bucket ${ARTIFACT_BUCKET} --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
    - .aws-sam/**/*
    - template.yaml
  exclude-paths:
    - node_modules/**/*
  discard-paths: no
  compression: GZIP
cache:
  paths:
    - functions/*/node_modules/**/*
